name: tob
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip:
    - aniso8601==10.0.0
    - blinker==1.9.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - Flask==3.1.0
    - Flask-RESTful==0.3.10
    - idna==3.10
    - itsdangerous==2.2.0
    - Jinja2==3.1.5
    - MarkupSafe==3.0.2
    - numpy==2.2.3
    - opencv-python==4.11.0.86
    - pillow==11.1.0
    - pytz==2025.1
    - requests==2.32.3
    - setuptools==75.8.0
    - six==1.17.0
    - urllib3==2.3.0
    - Werkzeug==3.1.3
    - wheel==0.45.1
  - python
